### ISSUE TITLE
Permission to access Greenlight

### ISSUE THREAD

**Issue by duyhieubui** [bespoke-silicon-group/bsg_manycore#149]
I tried to build and run the design. However, I do not have permission to check out submodule greenlight because it is not published yet.
My temporary solution is to delete this submodule from the local git.

**Comment by taylor-bsg** [comment]
Thanks for the report!

@vb000 since greenlight cannot be open sources, can you modify the checkout
submodule rule so that it explicitly checks out each submodule and skips
greenlight if it cannot access it? If there is a error/warning printed, try
to suppress it so that the out of the box experience is good.

**Comment by duyhieubui** [comment]
This issue has been solved by df58395b6b20de7b35172188d1e878fb0a5db106
