### ISSUE TITLE
risc-v toolchain building broken

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_manycore#158]
I run `make clean-all` and `make install-clean`. It fails in the middle.

cp: cannot stat ‘/mnt/bsg/diskbits/dcjung/bsg/bsg_manycore/software/riscv-tools/riscv-gnu-toolchain/install-newlib-nano/riscv32-unknown-elf/lib/./crt0.o’: No such file or directory
make[4]: *** [stamps/merge-newlib-nano] Error 1

**Comment by vb000** [comment]
We have removed crt from the our newlib to make it architecture independent. It's surprising that the parent repo (riscv-gnu-toolchain), explicitly copies hardcoded list of files installed by newlib. 

But the actual issue is, I didn't test the update by a clean installation of toolchain, as newlib was re-building correctly. @tommydcjung I tested the fix below by a clean installation. Could you volunteer to test it out on your end as well? Thanks!

https://github.com/bespoke-silicon-group/bsg_manycore/tree/toolchain_newlib_patch

**Comment by tommydcjung** [comment]
I tested it. seems to work now. can you create PR? thanks!

**Comment by tommydcjung** [comment]
actually fhello fails.

/bin/sh: /mnt/bsg/diskbits/dcjung/bsg/bsg_manycore/software/riscv-tools/riscv-install/bin/../riscv32-unknown-elf/bin/dramfs_mklfs: No such file or directory
make: *** [lfs.c] Error 127

**Comment by vb000** [comment]
Not sure... it worked fine when I did a clean install. Did you try cleaning first? `make clean-all`

**Comment by vb000** [comment]
That commit it's checking out is the latest commit on master:
https://github.com/riscv/riscv-newlib/commits/master

Don't know why you are seeing that error...

**Comment by tommydcjung** [comment]
yes I had make clean-all... still failing.

**Comment by drichmond** [comment]
Fetch?

**Comment by vb000** [comment]
Seems like a git quirk...

@duyhieubui's fix for CentOS 6's git:
`git submodule update --init --recursive riscv-newlib`

Same command that works on XOR (Cent OS 7)'s git:
`git submodule update --init --recursive --remote riscv-newlib`

XOR's version of git needs `--remote` for updating the submodule.

**Comment by vb000** [comment]
Fixed in latest toolchain update. 

@duyhieubui Sorry, I couldn't find a way to track a branch that works on older versions of git as well. I can help you find a workaround to install toolchain in your local copy. Let me know if you have any questions...

**Comment by duyhieubui** [comment]
Thank you for the information. I only tested 'make tools' and it works if '--remote' is removed. I will try to upgrade our git to v2.x.
