### ISSUE TITLE
Maybe vanilla_core has a bug

### ISSUE THREAD

**Issue by openriscv** [bespoke-silicon-group/bsg_manycore#194]
1. Maybe vanilla_core has a bug in bsg_manycore/v/vanilla_bean/vanilla_core.v file.
2. Line 791 should be modified to "assign stall_icache_store = icache_v_i & ~icache_yumi_o;"

**Comment by taylor-bsg** [comment]
Thank you for your contribution! We will take a look.

**Comment by tommydcjung** [comment]
Not a bug. When there is ifetch response and icache remote store arriving at the same time, ifetch gets higher priority (icache_yumi_o == 0). When there is only icache remote store, it stalls the pipeline and writes into the icache.

**Comment by taylor-bsg** [comment]
@openriscv Thanks for taking a look at the code. If you have a small test
case that exhibits the unexpected behavior, definitely send us the code so
we can track down the issue!

**Comment by openriscv** [comment]
The code in the vanilla_core.v file is shown below:
  
assign icache_yumi_o = icache_v_i & (~ifetch_v_i);

  assign icache_flush = flush | icache_miss_in_pipe;

  assign stall_icache_store = icache_v_i & icache_yumi_o;

Why stall_icache_store stall the pipeline when icache_v_i & icache_yumi_o.

**Comment by openriscv** [comment]
When there is ifetch response and icache remote store arriving at the same time, ifetch gets higher priority (icache_yumi_o == 0).
ifetch gets higher priority so it need to stall pipeline when ifetch response and icache remote store arriving at the same time,so i think line 791 should be modified to "assign stall_icache_store = icache_v_i & ~icache_yumi_o;"

**Comment by openriscv** [comment]
Can you explain why "when there is only icache remote store, it stalls the pipeline and writes into the icache".

**Comment by tommydcjung** [comment]
Since icache is implemented using single-port SRAM, we cannot read and write at the same time. Since the next instruction cannot be read, the PC cannot increment. On the other hand, ifetch response does not stall pipeline. "icache bubble" sends out the remote load packet to fetch the instruction from main memory in the EXE stage. "icache bubble" moves onto MEM stage, and stalls the pipeline until the ifetch response to arrive. When the ifetch response arrives, the fetched instruction is immediately written into the icache. Finally, the icache bubble moves onto WB, where it updates the PC, reads the fetched instruction, and resumes the pipeline.

**Comment by openriscv** [comment]
Thanks very much.

**Comment by drichmond** [comment]
Did we reach a resolution on this?
