### ISSUE TITLE
Computing node

### ISSUE THREAD

**Issue by amithmath** [bespoke-silicon-group/bsg_manycore#703]
Hi,

Can computing node be RISC-V 64? If yes, what changes are required bsg_manycore, bsg_replicant, etc.?

-Amit

**Comment by dpetrisko** [comment]
Major changes

bsg_manycore:
- going through and figuring out where 32b is assumed instead of data_width_p (hopefully not many places)
- minor changes to decoder and ALU to support 32/64b ops
- testbench/, machine/Makefile.include, Makefile changes to support 32/64b. Specifically adding a parameter for data_width/XLEN
- Build a new or multilib gnu-toolchain to support 64b
- updates to software/bsg_manycore_lib to templatize those functions and classes
- not necessary, but probably desired: changes to the address map, which is hardcoded to 32b. 

bsg_replicant:
- update to machines/Makefile.include, specifically data_width/XLEN
- updates to bsg_manycore_*_packet.h to templatize to 32/64b

There is probably more, but those are the major points. I think @mrutt92 was thinking about this at some point and he's a C++ wizard so he might have more to say on the software side

**Comment by amithmath** [comment]
Okay thanks

**Comment by amithmath** [comment]
Okay thanks
