### ISSUE TITLE
HW: issue in bsg_fpu_f2i

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#77]
Output seems to be wrong in this particular scenario. Expected output is 0x80000000.

![Screen Shot 2019-06-24 at 2 51 36 PM](https://user-images.githubusercontent.com/16723254/60055456-8ad33580-9692-11e9-973b-3f979e5da147.png)

testcase failing: `make fcvt_w.riscv_tests_run` in `software/spmd/bsg_riscv_tests`

**Comment by tommydcjung** [comment]
this is little tricky. it seems reasonable to think that 0xcf32d052 converts to negative zero (0x80000000). However, the target domain is "integer". 0x80000000 in integer is not negative zero, but it's a very large negative number in two's complement. Also, negative zero is a floating point concept. There is no negative zero for integers.

**Comment by taylor-bsg** [comment]
Makes sense! But is a risc-v test inconsistent with this?

**Comment by taylor-bsg** [comment]
Are you referring to this line of code?

https://github.com/riscv/riscv-tests/blob/a77db03bf0344cfc102d9957e1d58f0d2ece58d5/isa/rv64uf/fcvt_w.S#L26

Per the spec:

https://github.com/riscv/riscv-isa-manual/releases/download/draft-20190625-cc95103/riscv-spec.pdf  (page 67)

**If the rounded result is not representable in the destination format, it is clipped to the nearest value and the invalid  flag is set.**

0xcf32d05e is -3.0E9 per https://www.h-schmidt.net/FloatConverter/IEEE754.html
So, conversion to signed integer is not possible, because -3.0E9 <  -2^31 = -2,147,483,648. So the result should be 0x8000_0000 (-2,147,483,648), the smallest SInt32. That is what I am concluding?

**Comment by vb000** [comment]
Yes, that's the line. Thanks! We had missed this in the spec. Yeah, bsg_fpu_f2i has to be updated to match the latest spec.

**Comment by vb000** [comment]
All riscv isa test passing on tapeout_hb_rc0.3!
