### ISSUE TITLE
RFC: Trace-like (i.e. bind) performance counter module

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#95]
For the performance and energy evaluation we have discussed adding a trace-module-like performance counter module, that binds into specific modules and counts the number of operations that occur. For instance: 

For each Victim Cache:
- The number of cache hits/misses 
- Effective bandwidth

For each Core:
- Instruction mix
- Cycle Counter

For each Router: 
- Packets Transmitted
- Packets Stalled (?)
- Cycles Stalled (?)
- Effective bandwidth

There should be some non-intrusive way to call this and have it report results. For example, it could be called by the SPMD loader when a program begins and finishes execution. 

(@sampsyo, and Chris Batten have opinions on this too)

**Comment by sampsyo** [comment]
This could be super useful for evaluation purposes! And perhaps even beyond, when just trying to do garden-variety performance debugging. I also think you've gotten the right high-order counts that would be necessary too.

As a project-management thing, however, I want to be conscious that this could be deceptively hard—and because we don't have that much time left in the evaluation phase, if it's going to take too long, maybe we're better off getting these values from some other simulation strategy instead of hustling to try to make this work.

**Comment by taylor-bsg** [comment]
Hi, we will have this pretty soon. But you will need to use cosimulation or
manycore only simulation.

M
